### ISSUE TITLE
No files in color_corr, list index out of range

### ISSUE THREAD

**Issue by abhi-rf** [xingyi-li/s-dyrf#2]
Hey, thanks for your very cool work. I am trying to reproduce for one specific style image, and I did all of the steps mentioned in the readme. However, I run into the following issue for running with DNerf :

> Traceback (most recent call last):
>   File "ref_style_time.py", line 176, in <module>
>     trainer.train(25000, "style")
>   File "me/s-dyrf/hexplane/render/style_trainer_time.py", line 528, in train
>     related_rays_gt = related_rays_gts[tmpl_id % len(num_dict)]
> IndexError: list index out of range
> srun: error: node11: task 0: Exited with exit code 1

On investiogation, it comes in from `len(num_dict)` being 0

`num_dict = glob.glob(os.path.join(self.cfg.style.out_dir, "color_corr", "color_corr_*.pt"))`

This is because my color_corr folder is empty, I do not know why is that since I followed all the steps and made sure nothing was overlooked! 

Thanks for your help @xingyi-li !

**Comment by abhi-rf** [comment]
Update: Solved by starting the process again, the empty color_corr folder forced it to Preload without it having anything else inside! Thanks!!

**Comment by abhi-rf** [comment]
Hi! I get a similar issue while preparing the data again using all the steps in the readme. 

I get the issue at the following command `bash scripts/preprocess_dnerf_all.sh`, specifically the `python ref_regist_time.py `command

```
ic| 'Start ray registeration step'
ic| style_dict: {'color_pre': True,
                 'dataset_type': 'dnerf',
                 'scene_name': 'jumpingjacks',
                 'style_img': ['./dataset/ref_case/jumpingjacks_14/style_pencil_jumpingjacks.png'],
                 'style_name': 'jumpingjacks_14',
                 'tmpl_idx': [16],
                 'tmpl_idx_test': [2],
                 'tmpl_idx_train': None}
ic| "Loaded ckpt: ": 'Loaded ckpt: '
    cfg.systems.ckpt: 'log/dnerf/jumpingjacks/dnerf.th'
Loading data train (200): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:05<00:00, 37.88it/s]
Loading data test (20): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 40.36it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:45<00:00,  4.35it/s]
  0%|                                                                                                                                                 | 0/75 [00:45<?, ?it/s]
Traceback (most recent call last):
  File "ref_regist_time.py", line 272, in <module>
    depths = torch.cat(depths).cpu().numpy().reshape(len(cur_time_idx_list), H, W)
RuntimeError: torch.cat(): expected a non-empty list of Tensors
```

Please let me know what I am doing different as somewhere, an empty depth map is being returned! @xingyi-li
